[workspace]
resolver = "2"

members = [
    "day-one"
]

[workspace.package]
name = "adventOfCode-2024"
version = "0.1.0"
edition = "2021"
authors = ["Caleb Ekstrand <ekstrand.caleb@ekshore.net>"]

[workspace.dependencies]
