[workspace]
resolver = "2"

members = [
    "day-one",
    "day-two"
]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["Caleb Ekstrand <ekstrand.caleb@ekshore.net>"]

[workspace.dependencies]
